# Generated by Django 5.0.3 on 2024-03-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField()),
                ('d', models.IntegerField()),
                ('q', models.IntegerField()),
                ('seasonal_p', models.IntegerField()),
                ('seasonal_d', models.IntegerField()),
                ('seasonal_q', models.IntegerField()),
                ('s', models.IntegerField(default=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingdata',
            name='check_out',
        ),
    ]
