# Generated by Django 5.0.3 on 2024-03-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('nights', models.FloatField()),
                ('guest', models.IntegerField()),
                ('total', models.FloatField()),
                ('number_of_bookings', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('check_in', 'guest', 'total')},
            },
        ),
    ]
