# Generated by Django 5.0.3 on 2024-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_optimizationparameters_remove_bookingdata_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProphetOptimizationParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changepoint_prior_scale', models.FloatField()),
                ('seasonality_prior_scale', models.FloatField()),
                ('yearly_seasonality', models.BooleanField()),
                ('rmse', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prophet Optimization Parameter',
                'verbose_name_plural': 'Prophet Optimization Parameters',
            },
        ),
    ]
