# Generated by Django 5.0.3 on 2024-04-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_prophetoptimizationparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdata',
            name='guest',
            field=models.CharField(max_length=255),
        ),
    ]
