# Generated by Django 5.0.3 on 2024-04-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_alter_bookingdata_guest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingdata',
            unique_together={('check_in', 'nights', 'total')},
        ),
    ]
